# ref: https://jupyterbook.org/en/stable/customize/config.html

title: emurinson-paper
author: Ethan Murinson
execute:
  execute_notebooks: force

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year